class ScreenTextList {
  static const List<String> profileOptions = [
    'Yourself',
    'Brother',
    'Sister',
    'Daughter',
    'Son',
    'Relative'
  ];

  static const List<String> religions = [
    'Hindu',
    'Muslim',
    'Christian',
    'Sikh',
    'Buddhist',
    'Jain',
    'Zoroastrian',
    'Other'
  ];

  static const List<String> motherTongues = [
    'Hindi',
    'English',
    'Bengali',
    'Telugu',
    'Marathi',
    'Tamil',
    'Urdu',
    'Gujarati',
    'Kannada',
    'Odia',
    'Malayalam',
    'Punjabi',
    'Assamese',
    'Maithili',
    'Bhili/Bhilodi'
  ];

  static const Map<String, String> countryCodes = {
    'India': '+91',
    'USA': '+1',
    'UK': '+44',
    'Australia': '+61',
    'Canada': '+1',
    'China': '+86',
    'France': '+33',
    'Germany': '+49',
    'Japan': '+81',
    'Russia': '+7'
  };
  static const List<String> countries = [
    "India",
    "United States",
    "Canada",
    "Australia",
    "United Kingdom",
    "Germany",
    "France",
    "Japan",
    "China",
    "Brazil",
    "Russia",
    "South Africa",
    "Mexico",
    "Italy",
    "South Korea"
  ];
  static const List<String> rajasthanCities = [
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Alwar",
    "Bharatpur",
    "Pali",
    "Sikar",
    "Bundi",
    "Chittorgarh",
    "Jaisalmer",
    "Barmer",
    "Bhilwara",
    "Tonk",
    "Nagaur",
    "Churu",
    "Hanumangarh",
    "Dholpur",
    "Dungarpur"
  ];
  static const List<String> indianStates = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
  ];

  static List<String> indianFamilyTypes = [
    "Nuclear Family",
    "Joint Family",
    "Extended Family",
    "Single-Parent Family",
    "Blended Family"
  ];

  static List<String> employmentTypes = [
    "Government",
    "Private",
    "Farmer",
    "Business",
    "Semi-Government",
    "Other"
  ];

  static List<String> incomeRanges = [
    "0",
    "0-1 lakh",
    "1-1.5 lakh",
    "1.5-2.5 lakh",
    "2.5-4 lakh",
    "4-5 lakh",
    "5-6 lakh",
    "6-7 lakh",
    "7-8 lakh",
    "8-9 lakh",
    "9-10 lakh",
    "10-11 lakh",
    "11-12 lakh",
    "12-13 lakh",
    "13-14 lakh",
    "14-15 lakh",
    "More than 15 lakh"
  ];
  static List<String> degreesInIndia = [
    "Bachelor of Arts (BA)",
    "Bachelor of Science (BSc)",
    "Bachelor of Commerce (BCom)",
    "Bachelor of Engineering (BE)",
    "Bachelor of Technology (BTech)",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Computer Applications (BCA)",
    "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
    "Bachelor of Dental Surgery (BDS)",
    "Bachelor of Pharmacy (BPharm)",
    "Bachelor of Architecture (BArch)",
    "Bachelor of Education (BEd)",
    "Bachelor of Law (LLB)",
    "Bachelor of Physiotherapy (BPT)",
    "Bachelor of Science in Nursing (BSc Nursing)",
    "Bachelor of Social Work (BSW)",
    "Bachelor of Hotel Management (BHM)",
    "Bachelor of Design (BDes)",
    "Bachelor of Fine Arts (BFA)",
    "Bachelor of Computer Science (BCS)",
    "Bachelor of Veterinary Science (BVSc)",
    "Bachelor of Science in Agriculture (BSc Agri)",
    "Bachelor of Science in Information Technology (BSc IT)",
    "Bachelor of Science in Home Science (BSc Home Science)",
    "Bachelor of Science in Biotechnology (BSc Biotech)",
    "Bachelor of Science in Environmental Science (BSc Env Science)",
    "Bachelor of Library and Information Science (BLIS)",
    "Diploma in Engineering",
    "Diploma in Information Technology (ITI)",
    "Diploma in Pharmacy (D.Pharm)",
    "Diploma in Nursing",
    "Diploma in Management",
    "Master of Arts (MA)",
    "Master of Science (MSc)",
    "Master of Commerce (MCom)",
    "Master of Business Administration (MBA)",
    "Master of Technology (MTech)",
    "Master of Computer Applications (MCA)",
    "Master of Social Work (MSW)",
    "Master of Fine Arts (MFA)",
    "Master of Law (LLM)",
    "Doctor of Philosophy (PhD)",
    "Doctor of Medicine (MD)",
    "Master of Surgery (MS)",
    "Chartered Accountancy (CA)",
    "Cost and Management Accountancy (CMA)",
    "Company Secretary (CS)",
    "Post Graduate Diploma in Management (PGDM)",
    "Post Graduate Diploma in Computer Applications (PGDCA)"
  ];
  static const List<String> degrees = [
    "B.A. (Bachelor of Arts)",
    "B.Sc. (Bachelor of Science)",
    "B.Com. (Bachelor of Commerce)",
    "B.Ed. (Bachelor of Education)",
    "B.Tech. (Bachelor of Technology)",
    "B.E. (Bachelor of Engineering)",
    "BBA (Bachelor of Business Administration)",
    "BCA (Bachelor of Computer Applications)",
    "BHM (Bachelor of Hotel Management)",
    "BDS (Bachelor of Dental Surgery)",
    "MBBS (Bachelor of Medicine, Bachelor of Surgery)",
    "BAMS (Bachelor of Ayurvedic Medicine and Surgery)",
    "BHMS (Bachelor of Homeopathic Medicine and Surgery)",
    "BPT (Bachelor of Physiotherapy)",
    "LLB (Bachelor of Laws)",
    "M.A. (Master of Arts)",
    "M.Sc. (Master of Science)",
    "M.Com. (Master of Commerce)",
    "M.Ed. (Master of Education)",
    "M.Tech. (Master of Technology)",
    "M.E. (Master of Engineering)",
    "MBA (Master of Business Administration)",
    "MCA (Master of Computer Applications)",
    "MHM (Master of Hotel Management)",
    "MD (Doctor of Medicine)",
    "MS (Master of Surgery)",
    "MAMS (Master of Ayurvedic Medicine and Surgery)",
    "MPT (Master of Physiotherapy)",
    "LLM (Master of Laws)",
    "Ph.D. (Doctor of Philosophy)",
    "DIPLOMA (Diploma)",
    "ITI (Industrial Training Institute)",
    "PGD (Post Graduate Diploma)",
    "PGDM (Post Graduate Diploma in Management)",
    "CA (Chartered Accountant)",
    "ICWA (Institute of Cost and Works Accountants)",
    "CS (Company Secretary)",
    "CFA (Chartered Financial Analyst)",
    "CMA (Certified Management Accountant)",
    "CIT (Certified Information Technology)"
  ];

  static const List<String> maritalStatus = [
    'Single',
    'Married',
    'Divorced',
    'Widowed',
    'Separated',
  ];

  static const List<String> positions = [
    "Manager",
    "Employee",
    "In-Charge",
    "HR (Human Resources)",
    "Team Lead",
    "Supervisor",
    "Executive",
    "Assistant",
    "Consultant",
    "Coordinator",
    "Director",
    "Senior Analyst",
    "Junior Developer",
    "Senior Developer",
    "Project Manager",
    "Product Manager",
    "Marketing Specialist",
    "Sales Representative",
    "Customer Service Representative",
    "Accountant",
    "Engineer"
  ];
  static List<String> workingExperiences = [
    "0-1 year",
    "1-2 years",
    "2-3 years",
    "3-4 years",
    "4-5 years",
    "5-6 years",
    "6-7 years",
    "7-8 years",
    "8-9 years",
    "9-10 years",
    "More than 10 years"
  ];
}
